apiVersion: v1
kind: ConfigMap
metadata:
  name: sentinox-config
  namespace: sentinox
data:
  NODE_ENV: production
  PORT: "4000"
  REDIS_URL: redis://sentinox-redis:6379
  RATE_LIMIT_MAX: "200"
  WORKER_CONCURRENCY: "10"
  WS_PATH: /ws
